package com.example.composeapp

object SampleData {
    val Animals = listOf(
        "Alligator", "Bull", "Cow",
        "Antelope", "Buck", "Doe",
        "Baboon", "male", "Female",
        "Bear", "Boar", "Sow",
        "Bee", "Drone", "Queen",
        "Bird", "Cock", "Hen",
        "Butterfly", "Male", "Female",
        "Camel", "Bull", "Cow",
        "Cat", "Tomcat", "Queen",
        "Chicken", "Rooster", "Hen",
        "Crow", "Cock", "Hen",
        "Deer", "Buck", "Doe",
        "Dog", "Dog", "Bitch",
        "Dolphin", "Bull", "Cow",
        "Elephant", "Bull", "Cow",
        "Fox", "Reynard", "Vixen",
        "Giraffe", "Bull", "Doe",
        "Goat", "Buck", "Doe",
        "Hamster", "Buck", "Doe",
        "Heron", "Cock", "Hen",
        "Horse", "Stallion", "Mare",
        "Human", "Man", "Woman",
        "Kangaroo", "Buck", "Doe",
        "Leopard", "Leopard", "Leopardess",
        "Lion", "Lion", "Lioness",
        "Monkey", "Male", "Female",
        "Mosquito", "Male", "Female",
        "Mouse", "Buck", "Doe",
        "Panda", "Boar", "Sow",
        "Penguin", "Male", "Female",
        "Pig", "Boar", "Sow",
        "Rabbit", "Buck", "Doe",
        "Rat", "Buck", "Doe",
        "Shark", "Bull", "Female",
        "Sheep", "Buck", "Ewe",
        "Snake", "Male", "Female",
        "Spider", "Male", "Female",
        "Swan", "Cob", "Pen",
        "Tiger", "Tiger", "Tigress",
        "Whale", "Bull", "Cow",
        "Wolf", "Dog", "Bitch",
        "Zebra", "Stallion", "Mare"
    )
}